service: default
instance_class: F1
runtime: nodejs12

# https://qiita.com/sinmetal/items/017e7aa395ff459fca7c
automatic_scaling:
  target_cpu_utilization: 0.8 # default value '0.6'
  target_throughput_utilization: 0.8 # default value '0.6'
  max_instances: 1
  min_instances: 0
  max_idle_instances: 0 # default value 'automatic'
  min_idle_instances: 0
  min_pending_latency: 3000ms  # default value '30ms'
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
